config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: %i[index show new create]

  get "/:id", to: "home#redirect"
  get "/", to: "urls#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  has_many :visitors, dependent: :destroy

  before_validation :generate_shortlink

  ROOT_URL = "localhost:3000".freeze
  validates :link, presence: true, uniqueness: true, allow_blank: false
  validates :shortlink, presence: true, uniqueness: true, allow_blank: false

  def to_param
    shortlink
  end

  private

  def generate_shortlink
    self.shortlink = SecureRandom.uuid[0..5] if shortlink.blank?
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  belongs_to :url

  validates :ip_address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def redirect
    shortlink = Url.find_by(shortlink: params[:id])

    if shortlink.nil?
      render "home/error"
    else
      language = browser.accept_language.first
      visitor = Visitor.create(
        ip_address: request.remote_ip,
        browser: "#{browser.name} #{browser.full_version}",
        platform: "#{browser.platform.name} #{browser.platform.version}",
        device: browser.device.unknown? ? "computer" : browser.device.name,
        region: language.present? ? browser.accept_language.first.region : "Earth",
        url: shortlink
      )

      shortlink.visitors << visitor

      redirect_to shortlink.link
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :fetch_url, only: :show
  before_action :fetch_urls, only: [:index, :new]

  def index; end

  def show
    visitors = @url.visitors
    @dates = visitors.order("created_at DESC").pluck(:created_at).map(&:to_date).uniq
    date = params[:date].nil? ? @dates.first : params[:date].to_date
    @visitors_by_date = visitors.where("DATE(created_at) = ?", date)
    @visitor_count_by_hour = @visitors_by_date.group_by_hour_of_day(:created_at, format: "%-l %P").count
  end

  def new; end

  def create
    @url = Url.find_or_create_by!(url_params)

    redirect_to @url
  end

  private

  def fetch_url
    @url = Url.find_by(shortlink: params[:id])
  end

  def fetch_urls
    @urls = Url.all
  end

  def url_params
    params.permit(:link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/error.html.erb
<div class="ui center aligned container margin-top-25">
  <h1 class="ui header">Error! Shortlink invalid.</h1>
  <p><%= link_to("Back to home", "/") %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"/>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_with model: @url, url: urls_path, method: :post do |f| %>
  <div class="ui input">
    <%= f.text_field :link %>
  </div>
  <%= f.submit "Shorten", class: "ui primary button" %>
<% end %>

app/views/shared/_shortlink.html.erb
<div>
  <% if @url.present? %>
  <h2 class="ui header">Shortlink is <%= link_to("#{Url::ROOT_URL}/#{@url.shortlink}", "/#{@url.shortlink}", target: :blank) %></h2>
  <p>for <%= link_to(@url.link, @url.link, target: :blank) %></p>
  <h3 class="ui header">Visitors by day: <%= @visitors_by_date.count %></h3>
  <%= form_tag(url_path(id: @url.shortlink), method: "get") do %>
  <div class="field">
    <%= select_tag(:date, options_for_select(@dates), class: "ui dropdown") %>
    <%= submit_tag("Filter", class: "ui button", name: nil) %>
  </div>
  <% end %>
  <h3 class="ui header">Visitors by Hour</h3>
  <table class="ui celled striped table">
    <thead>
      <tr>
        <th>Hour</th>
        <th>Visitor Count</th>
      </tr>
    </thead>
    <tbody>
    <% @visitor_count_by_hour.each do |key, value| %>
      <tr>
        <% next if value == 0 %>
        <td><%= key %></td>
        <td><%= value %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <h3 class="ui header">Visitors Information</h3>
  <table class="ui celled striped table">
    <thead>
      <tr>
        <th>IP Address</th>
        <th>Browser</th>
        <th>Platform</th>
        <th>Device</th>
        <th>Region</th>
        <th>Created At</th>
      </tr>
    </thead>
    <tbody>
    <% @visitors_by_date.each do |v| %>
      <tr>
        <td><%= v.ip_address %></td>
        <td><%= v.browser %></td>
        <td><%= v.platform %></td>
        <td><%= v.device %></td>
        <td><%= v.region %></td>
        <td><%= v.created_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% end %>
</div>

app/views/shared/_title.html.erb
<div>
  <h1 class="ui header">URL Shortener</h1>
</div>

app/views/urls/index.html.erb
<div class="ui center aligned container margin-top-25">
  <%= render "shared/title" %>
  <table class="ui celled striped table">
    <thead>
      <tr>
        <th>Link</th>
        <th>Shortlink</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @urls.each do |u| %>
      <tr>
        <td><%= link_to(u.link, u.link, target: :blank) %></td>
        <td><%= link_to("#{Url::ROOT_URL}/#{u.shortlink}", "/#{u.shortlink}", target: :blank) %></td>
        <td class="center aligned"><a type="button" href="/urls/<%= u.shortlink %>" class="ui primary button">Stats</a></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <p><%= link_to("Back to home", "/") %></p>
</div>

app/views/urls/new.html.erb
<div class="ui center aligned container margin-top-25">
  <div class="v-centered">
    <%= render "shared/title" %>
  </div>
  <div class="v-centered">
    <%= render "shared/form" %>
  </div>
  <div class="margin-top-10">
    <a type="button" class="mini ui primary basic button" href="/urls">See all shortlinks</a>
  </div>
  <div class="margin-top-10">
    <h3 class="ui header">URLs Shortened Per Day</h3>
    <%= line_chart @urls.group_by_day(:created_at).count %>
  </div>
</div>

app/views/urls/show.html.erb
<div class="ui center aligned container margin-top-25">
  <div class="v-centered">
    <%= render "shared/title" %>
  </div>
  <div class="v-centered margin-top-10">
    <%= render "shared/shortlink", url: @url %>
  </div>
  <p><%= link_to("Back to home", "/") %></p>
</div>